### ISSUE TITLE
Parts are not added to the basket 

### ISSUE THREAD

**Issue by goran-mahovlic** [kitspace/1clickBOM#36]
I have checked on few computers, with firefox and on chrome, and it seams that parts are not longer added to the basket.
Firefox does not even open for example Mouser, and Chrome is opening but it shows empty basket.

On my computer it ends with loading - I did check other projects and I have same issue.

![loading](https://user-images.githubusercontent.com/4248736/154649515-1bc8acb3-f37c-4dfb-bdf4-962b009b6a98.png)

**Comment by kasbah** [comment]
Thanks for reporting! It should be fixed when your extension is updated to v1.8.3.

**Comment by goran-mahovlic** [comment]
Thank you! All working now!
